### ISSUE TITLE
all() returns expired values

### ISSUE THREAD

**Issue by ehuisman** [tylucaskelley/bx#1]
It seems that unlike `get()`, `all()` returns all values stored in a Bx instance regardless of their expiration status.

This is probably by design, and there are relatively straightforward workarounds. It is still quite confusing, so it would probably make sense to at least document the behavior somehow.

**Comment by tylucaskelley** [comment]
Fixed in https://github.com/tylucaskelley/bx/commit/0bf643b95aa59855c512175b3c70c51ea2293eb5
